GoogleCloudPlatform/pontem

.codecov.yml, .travis.yml, pom.xml
=> Add code coverage information.

USAGE.md
This is in reference to PR #74
=> Updating Usage docs to include more explicit comments about region.

pom.xml, src/main/java/com/google/cloud/pontem/BaseCloudSpannerDatabaseBackup.java, src/main/java/com/google/cloud/pontem/SerializedCloudSpannerDatabaseBackup.java, src/main/java/com/google/cloud/pontem/SerializedCloudSpannerDatabaseRestore.java, src/test/java/com/google/cloud/pontem/BaseCloudSpannerDatabaseBackupTest.java, src/test/java/com/google/cloud/pontem/SerializedCloudSpannerDatabaseBackupTest.java
=> Upgrading Beam to 2.5.0-SNAPSHOT in preparation for a forthcoming 2.5.0 release

.travis.yml, travis/run_e2e_tests.sh
Adding Matrix statement to our travis config so that the Avro and Serialized E2E tests can be run in parallel. Also updated our runner script to run the correct test suite based on the corresponding
parameter.
=> Updating Travis config so as to run E2E Tests in parallel

.travis.yml
Changing before_install to before_script so as to avoid Gradle being called during the install phase
=> Update travis.yml to avoid calling Gradle

.travis.yml, build.gradle
Adding test coverage with Jacoco to Java projects in Gradle and integrating the reports with Codecov in Travis
=> Adding test coverage to Gradle and integrating with Codecov

.travis.yml
[Root] Added conditional checks to ensure that if no known tags are matched in the commit message 
then run build and test everything.
=> [Root] Added conditional checks non-matched commits run everything

CloudSQLReplicator/google/cloud/pontem/sql/replicator/__init__.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/gcp_api_util.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/mysql_util.py, README.md
Added code to change user agent of Google Cloud API Client to use custom user agent string based on package info (name and version). Corrected mistakes in docstring for mysql_util.
=> Changed Google Cloud API Client to use custom user agent

CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/gcp_api_util.py
Add code for creating Cloud SQL instance, importing database from SQL file, and checking if a SQL operation is DONE. Adds custom Cloud SQL Replicator user agent to httplib2.Http.
=> Added code for SQL Admin functions.

.travis.yml, BigQueryWorkloadTester/build.gradle, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/BigQueryWorkloadTester.java, hooks/add-project-names-to-commit-msg, settings.gradle
[BigQueryWorkloadTester] [Root]  Adding initial skeleton for BigQueryWorkloadTester along with related changes to Travis and build hooks
=>  [BigQueryWorkloadTester] [Root]  Adding initial skeleton for BigQueryWorkloadTester

CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/cloudsql.py, hooks/python-lint-pre-commit
This will run pylint on the top most module for each file using the pylintrc of each project.
=> Added python lint pre commit hook. 

CloudSqlImportOptimization/README.md
Updating README with notes about mysqlclient, secure file priv and encoding instructions, and unix support. Also fixing some mispelled commands and breaking up long commands.
=> [Root] Updating README for CloudSqlImportOptimization

BigQueryWorkloadTester/build.gradle
[BigQueryWorkloadTester] Updating build.gradle with all the dependencies needed by BigQueryWorkloadTester.
=> [BigQueryWorkloadTester] Updating build.gradle with all the dependencies needed by BigQueryWorkloadTester.

BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/config/Configuration.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/config/WorkloadSettings.java, BigQueryWorkloadTester/src/main/resources/config.yaml, BigQueryWorkloadTester/src/main/resources/sample_config.yaml
[BigQueryWorkloadTester] Adding config files and the classes used to parse them into Java
=> [BigQueryWorkloadTester] Adding config files and the classes used to parse them into Java

BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/model/BigQueryResult.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/model/QueryResult.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/model/Status.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/model/WorkloadResult.java
[BigQueryWorkloadTester] Adding the *Result files that will hold Workload Execution results.
=> [BigQueryWorkloadTester] Adding the *Result files that will hold Workload Execution results.

BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/auth/BigQueryCredentialManager.java, BigQueryWorkloadTester/src/test/java/com/google/cloud/pontem/auth/BigQueryCredentialManagerTest.java, BigQueryWorkloadTester/src/test/resources/fakecreds.json
[BigQueryWorkloadTester] Adding BigQuery Credentials Manager and test
=> [BigQueryWorkloadTester] Adding BigQuery Credentials Manager and test

BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/runners/ConcurrentWorkloadRunner.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/runners/ConcurrentWorkloadRunnerFactory.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/runners/SerialQueryRunner.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/runners/callables/WorkloadRunnerCallable.java, BigQueryWorkloadTester/src/test/java/com/google/cloud/pontem/benchmark/runners/ConcurrentWorkloadRunnerTest.java, BigQueryWorkloadTester/src/test/java/com/google/cloud/pontem/benchmark/runners/SerialQueryRunnerTest.java, BigQueryWorkloadTester/src/test/java/com/google/cloud/pontem/benchmark/runners/callables/WorkloadRunnerCallableTest.java
[BigQueryWorkloadTester] Adding Workload Runners and their respective tests
=> [BigQueryWorkloadTester] Adding Workload Runners and their respective tests

BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/Benchmark.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/RatioBasedWorkloadBenchmark.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/WorkloadBenchmark.java, BigQueryWorkloadTester/src/test/java/com/google/cloud/pontem/benchmark/RatioBasedWorkloadBenchmarkTest.java, BigQueryWorkloadTester/src/test/java/com/google/cloud/pontem/benchmark/WorkloadBenchmarkTest.java
[BigQueryWorkloadTester] Adding benchmark classes that will execute workloads
=> [BigQueryWorkloadTester] Adding benchmark classes that will execute workloads

BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/result/JsonResultProcessor.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/result/JsonResultProcessorFactory.java, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/result/ResultFileWriter.java, BigQueryWorkloadTester/src/test/java/com/google/cloud/pontem/result/JsonResultProcessorTest.java
[BigQueryWorkloadTester] Adding classes that will take the workload results and convert them into json files for output
=> [BigQueryWorkloadTester] Adding classes that will take the workload results and convert them into json files for output

BigQueryWorkloadTester/build.gradle, BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/BigQueryWorkloadTester.java
[BigQueryWorkloadTester] Updating build.gradle with all the necessary dependencies and 
BigQueryWorkloadTester to it's alpha version.
=> [BigQueryWorkloadTester] Updating BigQueryWorkloadTester to it's alpha version.

CloudSQLReplicator/google/cloud/pontem/sql/replicator/cli/main.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/cloudsql.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/compute.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/gcp_api_util.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/mysql_util.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/storage.py, CloudSQLReplicator/pylintrc, CloudSQLReplicator/setup.py
Added CLI to collect configuration information from user for replication operation.
=> [CloudSQLReplicator] Added CLI to collect configuration information 

BigQueryWorkloadTester/src/main/java/com/google/cloud/pontem/benchmark/backends/BigQueryBackendFactory.java
s/bigquery-workload-tester/bigquery-workload/
=> [BigQueryWorkloadTester] Tweak the user-agent.

.travis.yml, CloudSQLReplicator/google/cloud/pontem/sql/replicator/cli/main.py
Log warning from Cloud SDK are making it hard to see what is going on in the CLI.
=> [CloudSQLReplicator] Suppress log warnings

CloudSQLReplicator/google/cloud/pontem/sql/replicator/cli/main.py
Added code to determine if host is in GCP, determine ip from metadata server and add allow firewall rule.
=> [CloudSQLReplicator] Add allow firewall rule if in GCP

.travis.yml, CloudSQLReplicator/google/cloud/pontem/sql/replicator/cli/main.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/gcp_api_util.py
Previous efforts to suppress warning from Google API Client did were not enough. Tested this on container.
=> Suppress warnings

CloudSQLReplicator/google/cloud/pontem/sql/replicator/cli/main.py, CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/mysql_util.py
Added MySQLDump automation for external (outside of GCP) dump per customer engineer documentation.
=> Added code for external mysqldump

CloudSQLReplicator/container/Dockerfile, CloudSQLReplicator/container/cloudbuild.yaml, CloudSQLReplicator/setup.py
Fixed cloudbuild.yaml and Dockerfile to kick off a build of the pontem-csr container on changes to dev branch.
=> Fixed cloud build and Dockerfile to be compatible with Cloud Build triggers.

CloudSQLReplicator/google/cloud/pontem/sql/replicator/util/iam.py
Added code to create service accounts, add roles and download associated keys.
=> [CloudSQLReplicator] Added code to create service accounts 
